apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: simple-deploy
  name: simple-deploy
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: simple-deploy
  type: LoadBalancer
status:
  loadBalancer: {}
